/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gpacalculator;

/**
 *
 * @author vidya
 */
public class QandAs extends javax.swing.JFrame {

    /**
     * Creates new form QandAs
     */
    public QandAs() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        qAndABkg1 = new javax.swing.JPanel();
        qAndAOptions = new javax.swing.JComboBox<>();
        getAnswerButton = new javax.swing.JButton();
        qAndAbkg2 = new javax.swing.JPanel();
        qAndATextArea = new javax.swing.JLabel();
        qAndATextArea2nd = new javax.swing.JLabel();
        qAndATextArea3rd = new javax.swing.JLabel();
        generatePdfButton = new javax.swing.JButton();
        qAndATitle = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.setText("jTextField1");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        qAndAOptions.setFont(new java.awt.Font("HP Simplified Jpan", 0, 20)); // NOI18N
        qAndAOptions.setForeground(new java.awt.Color(107, 153, 214));
        qAndAOptions.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Please select a question you would like an answer for.", "What does GPA stand for?", "How can I improve my GPA?", "Where can I view my grades (as a student at Midlo)?", "What grades do I need to get a desired GPA?", "How do I obtain a PDF report of my grades?" }));
        qAndAOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qAndAOptionsActionPerformed(evt);
            }
        });

        getAnswerButton.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        getAnswerButton.setForeground(new java.awt.Color(107, 153, 214));
        getAnswerButton.setText("Get Answer ");
        getAnswerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getAnswerButtonActionPerformed(evt);
            }
        });

        qAndAbkg2.setBackground(new java.awt.Color(107, 153, 214));
        qAndAbkg2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        qAndATextArea.setFont(new java.awt.Font("HP Simplified Jpan Light", 0, 20)); // NOI18N
        qAndATextArea.setForeground(new java.awt.Color(255, 255, 255));
        qAndATextArea.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        qAndATextArea2nd.setFont(new java.awt.Font("HP Simplified Jpan Light", 0, 20)); // NOI18N
        qAndATextArea2nd.setForeground(new java.awt.Color(255, 255, 255));
        qAndATextArea2nd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        qAndATextArea3rd.setFont(new java.awt.Font("HP Simplified Jpan Light", 0, 20)); // NOI18N
        qAndATextArea3rd.setForeground(new java.awt.Color(255, 255, 255));
        qAndATextArea3rd.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        generatePdfButton.setFont(new java.awt.Font("HP Simplified Jpan", 1, 18)); // NOI18N
        generatePdfButton.setForeground(new java.awt.Color(107, 153, 214));
        generatePdfButton.setText("Generate PDF");
        generatePdfButton.setEnabled(false);
        generatePdfButton.setOpaque(true);
        generatePdfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generatePdfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout qAndAbkg2Layout = new javax.swing.GroupLayout(qAndAbkg2);
        qAndAbkg2.setLayout(qAndAbkg2Layout);
        qAndAbkg2Layout.setHorizontalGroup(
            qAndAbkg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qAndAbkg2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(qAndAbkg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qAndATextArea2nd, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addComponent(qAndATextArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(qAndATextArea3rd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(generatePdfButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        qAndAbkg2Layout.setVerticalGroup(
            qAndAbkg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qAndAbkg2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(qAndATextArea, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qAndATextArea2nd, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qAndATextArea3rd, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(generatePdfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        qAndATitle.setFont(new java.awt.Font("HP Simplified Jpan", 1, 60)); // NOI18N
        qAndATitle.setForeground(new java.awt.Color(107, 153, 214));
        qAndATitle.setText("Question and Answer");

        javax.swing.GroupLayout qAndABkg1Layout = new javax.swing.GroupLayout(qAndABkg1);
        qAndABkg1.setLayout(qAndABkg1Layout);
        qAndABkg1Layout.setHorizontalGroup(
            qAndABkg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, qAndABkg1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(qAndATitle)
                .addGap(153, 153, 153))
            .addGroup(qAndABkg1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(qAndABkg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(qAndAbkg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(qAndABkg1Layout.createSequentialGroup()
                        .addComponent(qAndAOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(getAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        qAndABkg1Layout.setVerticalGroup(
            qAndABkg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qAndABkg1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(qAndATitle)
                .addGap(26, 26, 26)
                .addGroup(qAndABkg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(qAndAOptions, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(getAnswerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(qAndAbkg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qAndABkg1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(qAndABkg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void qAndAOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qAndAOptionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qAndAOptionsActionPerformed

    private void getAnswerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getAnswerButtonActionPerformed
        if (qAndAOptions.getSelectedItem().equals("Please select a question you would like an answer for.")) 
        {
            qAndATextArea.setText("");
            qAndATextArea2nd.setText("");
            qAndATextArea3rd.setText("");
        }

        if (qAndAOptions.getSelectedItem().equals("What does GPA stand for?"))
        {
            qAndATextArea.setText("GPA stands for Grade Point Average.");
            qAndATextArea2nd.setText("Basically, it translates all of your letter grades in to a certain value, and then divides it");
            qAndATextArea3rd.setText("by the total number of courses you have to yield your GPA.");
        }
        if (qAndAOptions.getSelectedItem().equals("How can I improve my GPA?")) 
        {
            qAndATextArea.setText("1. Ask for extra help in the subjects you are struggling on.");
            qAndATextArea2nd.setText("2. Revise your notes and practice everyday.");
            qAndATextArea3rd.setText("3. Attend all of your classes so you are aware of assignments and expectations.");
        }

        if (qAndAOptions.getSelectedItem().equals("How do I obtain a PDF report of my grades?")) 
        {
            qAndATextArea.setText("Please click on the Generate PDF Button below!");
            qAndATextArea2nd.setText("You can then select your desired format of the PDF.");
            qAndATextArea3rd.setText("Afterwards, a PDF of your inputted grades will download.");
        }
    }//GEN-LAST:event_getAnswerButtonActionPerformed

    private void generatePdfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generatePdfButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generatePdfButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QandAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QandAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QandAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QandAs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QandAs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton generatePdfButton;
    private javax.swing.JButton getAnswerButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel qAndABkg1;
    private javax.swing.JComboBox<String> qAndAOptions;
    private javax.swing.JLabel qAndATextArea;
    private javax.swing.JLabel qAndATextArea2nd;
    private javax.swing.JLabel qAndATextArea3rd;
    private javax.swing.JLabel qAndATitle;
    private javax.swing.JPanel qAndAbkg2;
    // End of variables declaration//GEN-END:variables
}
